# Generated by Django 5.0.2 on 2024-03-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nombre', 'apellido']},
        ),
        migrations.AlterModelOptions(
            name='mascota',
            options={'ordering': ['nombre']},
        ),
    ]
